%--------------------------------------------------------------------------
%
% Include logos in the four corners of plot specified by figure handle H
%
%--------------------------------------------------------------------------

% This file is part of the WavePacket program package for quantum-mechanical
% simulations, and subject to the GNU General Public license v. 2 or later.
%
% Copyright (C) 2004-2017 Burkhard Schmidt's group
%               2007-2009 Ulf Lorenz
%
% see the README file for license details.
    
function logo ()
global info plots

% Upper left: WavePacket name, program, and SVN revision number
string1 = info.package;
string2 = info.program;
string3 = info.version1;
annotation('textbox', ...
  'Position',[0.00 0.95 0.05 0.05], ...  % x y w h
  'HorizontalAlignment', 'left', ...
  'Interpreter', 'none', ...
  'LineStyle', 'none', ...
  'String',{ string1, string2, string3 }, ...
  'FitHeightToText','on', ...
  'FontName',   plots.style.font.name,  ...
  'FontSize',   plots.style.font.small, ...
  'FontWeight', plots.style.font.heavy);

% Upper right: Host name, date, and time
string1 = info.host_name;
string2 = date;
c = clock; 
string3 = strcat ( num2str(c(4),'%2.2i'), ':', num2str(c(5),'%2.2i'));
annotation('textbox', ...
  'Position',[0.70 0.95 0.30 0.05], ...  % x y w h
  'HorizontalAlignment', 'right', ...
  'Interpreter', 'none', ...
  'LineStyle', 'none', ...
  'String',{ string1, string2, string3 }, ...
  'FitHeightToText','on', ...
  'FontName',   plots.style.font.name,  ...
  'FontSize',   plots.style.font.small, ...
  'FontWeight', plots.style.font.heavy);

% Lower left: User name and MATLAB release
string1 = ['User: ' info.user_name];
string2 = ['MATLAB Release R' info.release];
annotation('textbox', ...
  'Position',[0.00 0.0 0.15 0.05], ...  % x y w h
  'HorizontalAlignment', 'left', ...
  'Interpreter', 'none', ...
  'String',{ string1 string2 }, ...
  'LineStyle', 'none', ...
  'FitHeightToText','on', ...
  'FontName',   plots.style.font.name,  ...
  'FontSize',   plots.style.font.small, ...
  'FontWeight', plots.style.font.heavy);

% Lower right: Full path name (if too long, truncate it) and SVN revision
string1 = info.path_name;
string2 = info.version2;
if numel(string1) > 48
	string1 = strcat('...', string1(end-44:end));
end
annotation('textbox', ...
  'Position',[0.70 0.0 0.30 0.05], ...  % x y w h
  'HorizontalAlignment', 'right', ...
  'Interpreter', 'none', ...
  'String',{ string1 string2 }, ...
  'LineStyle', 'none', ...
  'FitHeightToText','on', ...
  'FontName',   plots.style.font.name,  ...
  'FontSize',   plots.style.font.small, ...
  'FontWeight', plots.style.font.heavy);


