function Hd = getFilter
%GETFILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.1 and the DSP System Toolbox 9.3.
% Generated on: 08-Dec-2017 12:33:23

Fstop1 = 5;    % First Stopband Frequency
Fpass1 = 10;   % First Passband Frequency
Fpass2 = 20;   % Second Passband Frequency
Fstop2 = 25;   % Second Stopband Frequency
Astop1 = 60;   % First Stopband Attenuation (dB)
Apass  = 1;    % Passband Ripple (dB)
Astop2 = 60;   % Second Stopband Attenuation (dB)
Fs     = 200;  % Sampling Frequency

h = fdesign.bandpass('fst1,fp1,fp2,fst2,ast1,ap,ast2', Fstop1, Fpass1, ...
    Fpass2, Fstop2, Astop1, Apass, Astop2, Fs);

Hd = design(h, 'equiripple', ...
    'MinOrder', 'any');


