function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 08-May-2018 11:14:21

% Create figure
figure1 = figure('OuterPosition',[1 1 1920 895]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',2);
set(plot1(1),'DisplayName','Linear');
set(plot1(2),'DisplayName','NL - 1600 k3/k2');

% Create xlabel
xlabel('\eta');

% Create title
title('Transmittance curve for 5U system MIM model');

% Create ylabel
ylabel('Transmittance (dB)');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 2]);
box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',30);
% Create legend
legend(axes1,'show');

